version: "3"

volumes:
  turbotailer_local_postgres_data: {}
  turbotailer_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: turbotailer_local_django
    container_name: turbotailer_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: turbotailer_production_postgres
    container_name: turbotailer_local_postgres
    volumes:
      - turbotailer_local_postgres_data:/var/lib/postgresql/data
      - turbotailer_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:6
    container_name: turbotailer_local_redis

  celeryworker:
    <<: *django
    image: turbotailer_local_celeryworker
    container_name: turbotailer_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: turbotailer_local_celerybeat
    container_name: turbotailer_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: turbotailer_local_flower
    container_name: turbotailer_local_flower
    ports:
      - "5555:5555"
    command: /start-flower

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: turbotailer_local_frontend
    container_name: turbotailer_local_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
