# Generated by Django 4.2.2 on 2023-07-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=255, verbose_name="Name of Subscriber")),
                ("email", models.CharField(blank=True, max_length=255, verbose_name="Email of Subscriber")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Date of subscription")),
            ],
        ),
    ]
