# Generated by Django 4.2.2 on 2023-07-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_subscriber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="email",
            field=models.CharField(max_length=255, unique=True, verbose_name="Email of Subscriber"),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name of Subscriber"),
        ),
    ]
