# Generated by Django 4.2.2 on 2023-07-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_subscriber_email_alter_subscriber_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name of Subscriber"),
        ),
    ]
