# Generated by Django 4.2.2 on 2023-07-09 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WooCommerceStore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("consumer_key", models.CharField(blank=True, max_length=255, null=True)),
                ("consumer_secret", models.CharField(blank=True, max_length=255, null=True)),
                ("base_url", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="Store name")),
                (
                    "status",
                    models.CharField(
                        choices=[("Inactive", "Inactive"), ("Active", "Active")],
                        default="Inactive",
                        max_length=255,
                        verbose_name="Store status",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, choices=[("GPT3", "GPT3")], max_length=255, null=True, verbose_name="Model"
                    ),
                ),
                ("temperature", models.FloatField(default=0, verbose_name="Temperature")),
                ("max_tokens", models.IntegerField(default=256, verbose_name="Max tokens")),
                ("store_size", models.FloatField(default=0, verbose_name="Store size")),
                ("max_store_size", models.IntegerField(default=0, verbose_name="Max store size")),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stores",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("embed_timestamp", models.DateTimeField(blank=True, null=True)),
                ("size", models.IntegerField(default=0, verbose_name="Size")),
                (
                    "channel",
                    models.CharField(blank=True, choices=[("products", "Products")], max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Defines which fields will be fetched and included in the vectorstore",
                        null=True,
                        verbose_name="Fields",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to="stores.store",
                        verbose_name="Store",
                    ),
                ),
            ],
        ),
    ]
