# Generated by Django 4.2.2 on 2023-07-09 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("embeddings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="embeddingtask",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="embedding_tasks",
                to="stores.channel",
                verbose_name="Channel",
            ),
        ),
        migrations.AddField(
            model_name="embeddingtask",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="content",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content",
                to="stores.channel",
                verbose_name="Channel",
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content",
                to="stores.store",
                verbose_name="Store",
            ),
        ),
    ]
